services:
  www-mock:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    environment:
      - USE_MOCK_DATA=true
      - EFNAV_ENABLED=true
    networks:
      - default
